### ISSUE TITLE
Use guzzle 5 instead of guzzle 6?

### ISSUE THREAD

**Issue by markodobric** [stevenmaguire/trello-php#10]
Hi Steven,

I'm using your great trello wrapper in my project, but I have terrible dependencies hell. There a lot of other stuff which already use guzzle 5 and I have package conflict because your package use guzzle 6.

Is there a possibility that your package uses guzzle 5 instead of guzzle 6?

Thanks.

**Comment by stevenmaguire** [comment]
That will not be possible. There was a significant change in guzzle from 5 to 6, hence the major version bump, and the changes in 6 drive a lot of functionality in this project. Among the changes are support for PSR 7 Http Messages, some valuable standards that may improve your own project.

**Comment by ilijastuden** [comment]
How about if we refactor Http layer to use HttpPlug?

https://packagist.org/packages/php-http/httplug

This way Guzzle6 will be an suggested dependncy, and end user would be able to add any HTTP communication library as transport.

**Comment by ilijastuden** [comment]
Of course, we would make a Pull Request, no need for you to develop it. Just checking to see if you will consider merging it if we developed it.
