### ISSUE TITLE
Wheres the autoloader?

### ISSUE THREAD

**Issue by rappol** [stevenmaguire/trello-php#11]
Hi Steven,

im trying to use your repository but im unable to make it work. I've downloaded the zip file and upload it to my server (it's a shared one) and when i unzipped...there isnt a folder named Vendor....which is supposed to live the autoload.php

Can you tell me what im doing wrong?

**Comment by stevenmaguire** [comment]
This project is intended to be installed using the composer package manager. Composer installs this and other dependencies, then generates the autoload assets you appear to be missing.

If your project already uses composer, you can follow the installation guidelines in the read me. If your project does not already use composer, I recommend researching how to get started with composer at getcomposer.org.

If manual deployment via FTP is your only option, I suggest using composer to build your solution locally then upload the entire built solution to the web server.
