### ISSUE TITLE
Error in Traits/ConfigurationTrait.php on line 14

### ISSUE THREAD

**Issue by rappol** [stevenmaguire/trello-php#12]
Hi there,

i finnaly installed the project using composer, configured everything locally (the example.php file) and uploaded everything to the server to test it and im getting this error:

> Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /**MY_HOME_DIRECTORY**/trelloTest/vendor/stevenmaguire/trello-php/src/Traits/ConfigurationTrait.php on line 14

Im using PHP version    5.4.43 at the server...is it enough?

This is line 14 at ConfigurationTrait.php

`return forward_static_call_array([Configuration::class, 'has'], func_get_args());`

**Comment by stevenmaguire** [comment]
You will need at least php 5.5

https://wiki.php.net/rfc/class_name_scalars

**Comment by rappol** [comment]
hmm... is there a solution to use this project without php 5.5? Maybe not using the Traits...

Do you suggest any workaround?

**Comment by stevenmaguire** [comment]
No workaround. PHP 5.4 is not supported.

**Comment by rappol** [comment]
O nice..i was able  to switch to PHP 5.5 and now it works, thanks Steven.

Can i suggest you to update the ReadMe file or make a note somewhere else to indicate it's necessary PHP 5.5? I think its worth it.

**Comment by stevenmaguire** [comment]
I think adding the requirement to composer.json and README sound like a great idea. Would you be up for making those changes and submitting a PR?

**Comment by rappol** [comment]
I never did a PR before in github but im glad to help. I've started to read how to contribute, as soon as i figured it out i will do that. If i have any doubts can i contact you in here?

**Comment by stevenmaguire** [comment]
Yes. Please do. You're going to be great.
