### ISSUE TITLE
cURL error 7 :  Failed to connect to trello.com port 443: Timed out

### ISSUE THREAD

**Issue by theovaldi** [stevenmaguire/trello-php#14]
Hello Guys,

I'm having a problem when i'm trying to use cURL, the error was like this : 

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to trello.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186 Stack trace: #0 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(45): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\TRELLO\trello\ve in C:\xampp\htdocs\TRELLO\trello\vendor\stevenmaguire\trello-php\src\Http.php on line 272

I already try to google this kind of problem and how to handle them, but unfortunately it didn't help mine, can someone help me to fix this error? is it because Firewall block the Port? the network i use is my company's network..

**Comment by stevenmaguire** [comment]
These issues are typically related to your network configuration and not the code within the trello-php package. Contact your network administrator.

**Comment by theovaldi** [comment]
thank you so much steven, very appreciate your help..

**Comment by theovaldi** [comment]
@stevenmaguire heyy steve, sorry to disturb your time, i wanna ask you, if i use proxy will this error still occured? 

i try this, and failed, is it because my code didn't work? or still because the network configuration?

$url = 'https://google.com';
$proxy = '172.16.5.23';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_PROXY, $proxy);
curl_setopt($ch, CURLOPT_PROXYPORT, '8080');
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 1);
$curl_scraped_page = curl_exec($ch);
