### ISSUE TITLE
cURL error 7: Failed to connect to trello.com port 443: Timed out 

### ISSUE THREAD

**Issue by theovaldi** [stevenmaguire/trello-php#15]
Hi
I get error only if i connect internet using proxy
like this (full error code attached) "cURL error 7: Failed to connect to trello.com port 443: Timed out "

Can help me to put proxy setting
in my code

$client = new \Stevenmaguire\Services\Trello\Client(array(
    'domain' => 'https://trello.com',
    'key' => 'my_key',
    'secret' => 'my_code',
    'name' => 'My sweet trello enabled app',
    'callbackUrl' => $currentUrl,
    'expiration' => 'never',
    'scope' => 'read',
    'token' => 'my_token'
));

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to trello.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186 Stack trace: #0 C:\xampp\htdocs\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\trello\vendor\guzzlehttp\guzzle\src\Handler\ in C:\xampp\htdocs\trello\vendor\stevenmaguire\trello-php\src\Http.php on line 272

Thanks with Regards

**Comment by stevenmaguire** [comment]
These issues are typically related to your network configuration and not the code within the trello-php package. Contact your network administrator.
