### ISSUE TITLE
How to add proxy in trello-php

### ISSUE THREAD

**Issue by theovaldi** [stevenmaguire/trello-php#16]
Dear All
I try to get data trello using trello-php
but in my office require proxy to hit the internet.
Can show me the right way to put proxy in the code

thankyou

$client = new \Stevenmaguire\Services\Trello\Client(array(
    //'domain' => 'https://trello.com',
    'key' => 'my_key',
    'secret' => 'my_secret',
    'name' => 'My sweet trello enabled app',
    'callbackUrl' => $currentUrl,
    'expiration' => 'never',
    'scope' => 'read',
    'token' => 'my_token'
    //'proxy' => '172.16.5.23:8080'
));

**Comment by stevenmaguire** [comment]
I've just cut a new release of version 0.4.0 which should support the proxy setting.

https://github.com/stevenmaguire/trello-php#configure-the-client

The values you set as the `proxy` configuration key are directly passed into the Guzzle HTTP client, so you should spend time understanding how Guzzle handles that information. This package is not responsible for proxy or http logic, just configuration of the Guzzle Client.

http://docs.guzzlephp.org/en/latest/request-options.html#proxy
