### ISSUE TITLE
cURL Error 18 : transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by theovaldi** [stevenmaguire/trello-php#18]
Hello Steven,

The Code works perfectly fine now, and i can call Board, and List using proxy, except for Cards..
i can get few card, but when i try to get all board card, it give me this error: 

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 18: transfer closed with outstanding read data remaining (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:188 Stack trace: #0 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(151): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(104): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(45): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\TRELLO\trello\ in C:\xampp\htdocs\TRELLO\trello\vendor\stevenmaguire\trello-php\src\Http.php on line 273

i already try to change $conf[CURLOPT_HTTPHEADER][] = 'Expect:'; in CurlFactory.php into $conf[CURLOPT_HTTPHEADER][] = 'Expect: 100 - continue'; it fixed this error, but another error continue , the error was like this : 

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 56: Received HTTP code 417 from proxy after CONNECT (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:188 Stack trace: #0 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(151): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(104): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\TRELLO\trello\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(45): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\TRELLO\trello\vendo in C:\xampp\htdocs\TRELLO\trello\vendor\stevenmaguire\trello-php\src\Http.php on line 273

how can i fix this error? and what is the cause of this error ? 
Thank You so much for your help Steven.. every help from others will be appreciated too.

Best Regards,
-Me

**Comment by sakalauskas** [comment]
Getting the same error.

**Comment by stevenmaguire** [comment]
I am sorry to hear that you are experiencing a similar issue. As has been discussed many times, this issue is very likely caused by networking related issues rather than the code in this project. 

Please refer to a response in the duplicative issue report on the guzzle project: https://github.com/guzzle/guzzle/issues/1600#issuecomment-249768516
