### ISSUE TITLE
Explain in the docs how to use this

### ISSUE THREAD

**Issue by ReekenX** [stevenmaguire/trello-php#2]
I finally got it working!

You should mention in the README (or separate docs) how to start using this software.

How to get Developer Key: https://trello.com/app-key

How to get Token: https://trello.com/docs/gettingstarted/index.html#getting-a-token-from-a-user

How to get board ID: https://trello.com/docs/gettingstarted/index.html#introduction

Without researching how to retrieve those three you can not actually use example code you gave in README.

**Comment by stevenmaguire** [comment]
Thanks for the feedback; I'm glad the project is proving useful. 

Documentation in almost all projects could use perpetual improvement and this is no exception. What kind of solution would you propose? Would you mind drafting some changes and creating a pull request?

**Comment by stevenmaguire** [comment]
I've updated the documentation to include this.

**Comment by ReekenX** [comment]
Great! Thanks for fast update.

Next time will try to give pull request for things I can fix myself.
