### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by bzhang4sacstate** [stevenmaguire/trello-php#21]
A newbie question/problem:  Here is what I did:
```
$ git clone https://github.com/stevenmaguire/trello-php.git
$ cd trello-php
$ composer require stevenmaguire/trello-php
```

> Using version ^0.4.0 for stevenmaguire/trello-php
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for stevenmaguire/trello-php dev-master -> satisfiable by stevenmaguire/trello-php[dev-master].
>     - Can only install one of: stevenmaguire/trello-php[0.4.0, dev-master].
>     - Installation request for stevenmaguire/trello-php ^0.4.0 -> satisfiable by stevenmaguire/trello-php[0.4.0].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

What should I do now?

**Comment by stevenmaguire** [comment]
Welcome to the world of php package management! I believe what you just attempted to do was install the package inside the package :)

If your goal is to USE this package in another project, you should first create a separate project, configured for use with composer, then do `composer require stevenmaguire/trello-php`.

If your goal is to CONTRIBUTE to this package, you would clone this repo then do `composer install` and begin building.
