### ISSUE TITLE
support of paging?

### ISSUE THREAD

**Issue by bzhang4sacstate** [stevenmaguire/trello-php#22]
Hi Steven,

Is paging (https://developers.trello.com/get-started/intro#paging) supported with this implementation?  I am trying to get all cards of a board and all the actions of a card.

Thanks

**Comment by stevenmaguire** [comment]
Yes, I believe it does support that. Give this a try. I've just added a test case to demonstrate and exercise this functionality. 

```php
$parameters = ['before' => '2016-11-30'];
$cards = $client->getBoardCards('some-board-id', $parameters);
```
