### ISSUE TITLE
Can't add attachments to card

### ISSUE THREAD

**Issue by mariuswilms** [stevenmaguire/trello-php#3]
I need to add attachments/files to an existing card. I've tried the following and get a 400 Bad Request response, for each.

```
$client->addCardAttachment($card->id, ['file' => '/path/to/an/image.png']);
$client->addCardAttachment($card->id, ['file' => '@/path/to/an/image.png']);
$client->addCardAttachment($card->id, ['file' => fopen('/path/to/an/image.png', 'rb')]);

$client->addCardAttachment($card->id, [
'multipart' => [
  ['name' => 'file', 'contents' => fopen('/path/to/an/image.png', 'rb')]
]]);
```

http://docs.guzzlephp.org/en/latest/quickstart.html?highlight=multipart#sending-form-files
https://developers.trello.com/advanced-reference/card#post-1-cards-card-id-or-shortlink-attachments

**Comment by stevenmaguire** [comment]
Yikes! I will take a look.

**Comment by stevenmaguire** [comment]
There was in fact some code that needed to change to make this work as expected. I've added this code and updated the test suite. A new release has been cut for this, 0.3.5. Please update your project and give it a try again. 

The `file` attribute will accept a resource, as demonstrated below, a `string` that represents an object in php://temp, or an instance of `Psr\Http\Message\StreamInterface`.

``` php
$attributes = [
    'name' => 'Cheddar Bo is delicious!',
    'file' => fopen('/path/to/cheddar-bo.jpg', 'r'),
    'mimeType' => 'image/jpeg',
    'url' => null
];

$result = $client->addCardAttachment($cardId, $attributes);
```

**Comment by mariuswilms** [comment]
This is great - thanks a lot.

**Comment by mariuswilms** [comment]
Works!

**Comment by stevenmaguire** [comment]
Hooray! Happy attaching!

![prance](http://axisofstevil.s3.amazonaws.com/stuff/prance.gif)
