### ISSUE TITLE
Get board owners

### ISSUE THREAD

**Issue by markodobric** [stevenmaguire/trello-php#8]
Hello Steven.

I'm using your package to interact with trello and I want to get board owners by board ID. But I can't find api method that responds to this call (there is only `$client->getBoardMember($boardId, $memberId)` ).

I need method which call this end point: `https://api.trello.com/1/boards/4eea4ffc91e31d1746000046/members?filter=owners&key=[application_key]&token=[optional_auth_token]`

Thanks.

**Comment by stevenmaguire** [comment]
The majority of the methods are not explicitly declared in the project as they use a lot of reusable code. 

You can always check the [api guide](https://github.com/stevenmaguire/trello-php/blob/master/API-GUIDE.md) or the configuration array in the [ApiMethodsTrait](https://github.com/stevenmaguire/trello-php/blob/master/src/Traits/ApiMethodsTrait.php#L12).

The package does support your use case and the following should work.

``` php
$members = $client->getBoardMembers(
    $boardId, 
    ['filter' => 'owner']
);
```

Please try this and let me know if something else comes up.

**Comment by markodobric** [comment]
Yes, it works. But small correction: `['filter' => 'owners']` instead of `['filter' => 'owner']`

Thanks. :)
