### ISSUE TITLE
User email is NULL

### ISSUE THREAD

**Issue by markodobric** [stevenmaguire/trello-php#9]
Hi Steven.

I want to get all user information including the email. But when I call:

`$user = $client->getMember(
$userId, 
    ['fields' => 'email,username,fullName,avatarHash']
);`,

email property is NULL.

`{
  ["id"]=>
  string(24) "user id"
  ["email"]=>
  NULL
  ["username"]=>
  string(17) "username"
  ["fullName"]=>
  string(18) "Full Name"
  ["avatarHash"]=>
  string(32) "avatar hash"
}`

Please can you help me?

**Comment by stevenmaguire** [comment]
Your OAuth scope needs to include `account` to access that information. It should be `read,write,account`

**Comment by markodobric** [comment]
Yes, my OAuth scope is included `read,write,account`. But I got email value only for myself, not for other users (email is still NULL). :(

**Comment by stevenmaguire** [comment]
Yeah, I don't think the Trello API allows you to view email addresses of other users.
